### ISSUE TITLE
Draw use case diagrams

### ISSUE THREAD

**Issue by S1NEDIO** [PE-Pmi-31-2020/read-books#2]

**Comment by VictoriaBuhai** [comment]
<img width="814" alt="usecase" src="https://user-images.githubusercontent.com/61114583/94534183-c1f6a600-0248-11eb-92a1-6362e8a02672.png">

**Comment by VictoriaBuhai** [comment]
![usecase](https://user-images.githubusercontent.com/61114583/95124117-a2391380-075b-11eb-8dac-2b26a293ffb3.png)
