### ISSUE TITLE
Create uml diagram

### ISSUE THREAD

**Issue by S1NEDIO** [PE-Pmi-31-2020/read-books#5]

**Comment by VictoriaBuhai** [comment]
<img width="468" alt="UML_Database" src="https://user-images.githubusercontent.com/61114583/95679197-d425fc00-0bd9-11eb-84fb-b61f3e07f0b7.png">

**Comment by VictoriaBuhai** [comment]
![UML_database](https://user-images.githubusercontent.com/61114583/95679275-5a424280-0bda-11eb-95aa-1273b5522b2b.jpg)
